sonar.projectKey=earelin_adr-tools-alt
sonar.organization=earelin
sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippyReport.reportPaths=target/clippy.json
sonar.sourceEncoding=UTF-8
sonar.sources=src